### ISSUE TITLE
[mingw64] [MPV] module 'socket' has no attribute 'TCP_NODELAY'

### ISSUE THREAD

**Issue by mason1171** [m-ab-s/media-autobuild_suite#1767]
Suite Output
``` bash
┌ mpv git  ............................................ [Recently updated]
├ Running bootstrap...
Likely error (tail of the failed operation logfile):
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1417, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 923, in connect
    self.sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
AttributeError: module 'socket' has no attribute 'TCP_NODELAY'
bootstrap failed. Check C:/media-autobuild_suite/build/mpv-git/ab-suite.bootstrap.log
```
[logs.zip](https://0x0.st/iwmR.zip)
[ab-suite.bootstrap.log](https://github.com/m-ab-s/media-autobuild_suite/files/4963987/ab-suite.bootstrap.log)

**Comment by masterkivat** [comment]
Just had this same error during the 32-bit compiles.

22:32:30   Running git update for mpv...
22:32:31 ┌ mpv git  .................................. [Recently updated]
22:32:31 ├ Running bootstrap...
Likely error (tail of the failed operation logfile):
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1417, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 923, in connect
    self.sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
AttributeError: module 'socket' has no attribute 'TCP_NODELAY'

[iwuz.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4964355/iwuz.zip)

**Comment by mason1171** [comment]
So we just downgrade Python

**Comment by 1480c1** [comment]
I guess, either that or wait for @lazka to merge and rebuild his fix

**Comment by mason1171** [comment]
Ok, Im trying it again after upgrading for 3.7.4 to 3.8.4

**Comment by mason1171** [comment]
Despite upgrading, I still get the same error

**Comment by mc0re** [comment]
Same error:  [logs.zip](https://0x0.st/iw4R.zip)

**Comment by lazka** [comment]
Should be fixed now

**Comment by 1480c1** [comment]
running now to test

**Comment by 1480c1** [comment]
seems to work, @mason1171 can you confirm?

**Comment by mason1171** [comment]
How can I update this script without losing my progress?

**Comment by 1480c1** [comment]
are you currently running a build?

you can either wait or you can cancel it since it will not delete anything you have already built.

if you want to update the scripts from the suite, you can either use git and git pull or just manually download and overwrite the scripts

**Comment by mason1171** [comment]
Its not currently running. Are you saying just copy the root level of the new folder over the old one?

**Comment by 1480c1** [comment]
Yep, the only things that really matter between runs is the files under local64, msys64, and some ini and txt files under build

**Comment by mason1171** [comment]
Thanks. Thats exactly what I need to know

**Comment by 1480c1** [comment]
@mason1171 any update? if not, I will close the issue

**Comment by mason1171** [comment]
@1480c1 Im sorry. The build was successful. I just gotta move the files to their appropriate locations. Should I close the issue?

**Comment by 1480c1** [comment]
It's fine, thanks for the confirmation
