### ISSUE TITLE
Error SVT-AV1-git during complie

### ISSUE THREAD

**Issue by umpol69** [m-ab-s/media-autobuild_suite#1815]
Hello,

I try to build 1 day and always get this error

`14:46:46 ┌ SVT-AV1 git  .............................. [Recently updated]
14:46:46 ├ Running cmake...
14:46:51 ├ Running build...
Likely error (tail of the failed operation logfile):
[2/2] Linking C executable ..\Bin\Release\SvtAv1EncApp.exe
FAILED: ../Bin/Release/SvtAv1EncApp.exe
cmd.exe /C "cd . && C:\media-autobuild_suite-master\msys64\mingw64\bin\ccache.exe  clang -mtune=generic -O2 -pipe -Wall -Wextra -Wformat -Wformat-security -mxsave -fno-asynchronous-unwind-tables -O3 -DNDEBUG  -pipe -static-libgcc -static-libstdc++ third_party/safestringlib/CMakeFiles/safestringlib.dir/dummy.c.obj Source/App/EncApp/CMakeFiles/SvtAv1EncApp.dir/EbAppConfig.c.obj Source/App/EncApp/CMakeFiles/SvtAv1EncApp.dir/EbAppContext.c.obj Source/App/EncApp/CMakeFiles/SvtAv1EncApp.dir/EbAppInputy4m.c.obj Source/App/EncApp/CMakeFiles/SvtAv1EncApp.dir/EbAppMain.c.obj Source/App/EncApp/CMakeFiles/SvtAv1EncApp.dir/EbAppProcessCmd.c.obj Source/App/EncApp/CMakeFiles/SvtAv1EncApp.dir/EbTime.c.obj  -o ..\Bin\Release\SvtAv1EncApp.exe -Wl,--major-image-version,0,--minor-image-version,0  ../Bin/Release/libSvtAv1Enc.a  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
clang: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]
C:\media-autobuild_suite-master\msys64\mingw64\bin\ld: Source/App/EncApp/CMakeFiles/SvtAv1EncApp.dir/EbAppConfig.c.obj:EbAppConfig.c:(.text+0x2c78): undefined reference to `strnlen_s'
C:\media-autobuild_suite-master\msys64\mingw64\bin\ld: Source/App/EncApp/CMakeFiles/SvtAv1EncApp.dir/EbAppConfig.c.obj:EbAppConfig.c:(.text+0x2cb6): undefined reference to `strnlen_s'
C:\media-autobuild_suite-master\msys64\mingw64\bin\ld: Source/App/EncApp/CMakeFiles/SvtAv1EncApp.dir/EbAppConfig.c.obj:EbAppConfig.c:(.text+0x2cd3): undefined reference to `strnlen_s'
C:\media-autobuild_suite-master\msys64\mingw64\bin\ld: Source/App/EncApp/CMakeFiles/SvtAv1EncApp.dir/EbAppConfig.c.obj:EbAppConfig.c:(.text+0x32e7): undefined reference to `strnlen_s'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
build failed. Check C:/media-autobuild_suite-master/build/SVT-AV1-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
14:46:54   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/il8Z.zip
Copy and paste [logs.zip](https://0x0.st/il8Z.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
`

How to resolve this problem ?

**Comment by umpol69** [comment]
I tried to delete "SVT-AV1-git" dir as recommend but script auto generate it again

my /build/media-autobuild_suite.ini set "svtav1=2"

`[compiler list] 
arch=3
license2=1
standalone=1
vpx2=1
aom=1
rav1e=1
dav1d=1
libavif=1
x2643=1
x2652=1
other265=1
svthevc=1
xvc=1
vvc=1
svtav1=2
svtvp9=2
flac=2
fdkaac=1
faac=1
exhale=1
mediainfo=1
soxB=1
ffmpegB2=1
ffmpegUpdate=1
ffmpegChoice=1
mp4box=1
rtmpdump=1
mplayer2=2
mpv=2
vlc=2
bmx=2
curl=1
ffmbc=1
cyanrip2=1
redshift=1
ripgrep=1
jq=1
jo=1
dssim=1
avs2=1
CC=1
cores=8
deleteSource=1
strip=1
pack=2
logging=1
updateSuite=1
timeStamp=1
ccache=1
noMintty=2
`

**Comment by moob158** [comment]
Give me this error too

**Comment by j-mas** [comment]
Same here!

**Comment by wiiaboo** [comment]
@1480c1 is probably investigating as it might've been caused by https://github.com/AOMediaCodec/SVT-AV1/pull/1498

**Comment by 1480c1** [comment]
I guess maybe clang doesn't have some of the str*_s functions since it seems mingw-w64 gcc compiled fine https://github.com/AOMediaCodec/SVT-AV1/runs/1135250161

Maybe I should make it check if the function is linkable and set a macro that way

**Comment by dloneranger** [comment]
Same fail with mingw64 as well
F:/VSProjects2019/FF/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: Source/App/EncApp/CMakeFiles/SvtAv1EncApp.dir/EbAppConfig.c.obj:EbAppConfig.c:(.text+0x3412): more undefined references to `strnlen_s' follow

**Comment by 1480c1** [comment]
Closed based on upstream
