### ISSUE TITLE
[mingw64] [svt-hevc|svt-vp9|vvdec] ffmpeg build error caused by their patchs

### ISSUE THREAD

**Issue by ambitiuswisdom** [m-ab-s/media-autobuild_suite#3136]
``` bash
 Running git update for ffmpeg ...
┌ ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
├ Installing clang... done
├ Compiling shared FFmpeg...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
dlltool -m i386:x86-64 -d libswscale/swscale-10.def -l libswscale/swscale.lib -D swscale-10.dll
CC	libavcodec/libsvt_hevc.o
src/libavcodec/libsvt_hevc.c:571:8: error: 'AVCodec' has no member named 'pix_fmts'
  571 |     .p.pix_fmts     = (const enum AVPixelFormat[]){ AV_PIX_FMT_YUV420P,
      |        ^~~~~~~~
src/libavcodec/libsvt_hevc.c:571:23: error: initialization of 'const char *' from incompatible pointer type 'const enum AVPixelFormat *' [-Wincompatible-pointer-types]
  571 |     .p.pix_fmts     = (const enum AVPixelFormat[]){ AV_PIX_FMT_YUV420P,
      |                       ^
src/libavcodec/libsvt_hevc.c:571:23: note: (near initialization for 'ff_libsvt_hevc_encoder.p.name')
make: *** [/build/ffmpeg-git/ffbuild/common.mak:83: libavcodec/libsvt_hevc.o] Error 1
make failed. Check D:/mabs/build/ffmpeg-git/build-shared-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...
```
May be caused by https://github.com/FFmpeg/FFmpeg/commit/38221d0ec9d835e42125c4ff9c71214e27049b24 ,which fully remove `pix_fmts`. So, the [patch](https://raw.githubusercontent.com/1480c1/SVT-HEVC/master/ffmpeg_plugin/master-0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch) this script use to let ffmpeg support svt-hevc is no longer useful.

[logs.zip](https://github.com/user-attachments/files/29286506/logs.zip)

**Comment by ambitiuswisdom** [comment]
Same thing happens to svt-vp9 and vvdec
