### ISSUE TITLE
gpac error

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1995]
Thought i would compile a new set of ffmpeg binaries and this happen during the course........

  Running git clone for gpac...
┌ gpac git  ........................................... [Recently updated]
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
make[2]: Entering directory '/build/gpac-git/build-32bit/applications/gpac'
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.3.0/../../../../i686-w64-mingw32/bin/ld.exe: ../../bin/gcc\libgpac_static.a(quickjs-libc.o):quickjs-libc.c:(.text+0xc52): undefined reference to `pipe'
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.3.0/../../../../i686-w64-mingw32/bin/ld.exe: ../../bin/gcc\libgpac_static.a(quickjs-libc.o):quickjs-libc.c:(.text+0x5360): undefined reference to `pipe'
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.3.0/../../../../i686-w64-mingw32/bin/ld.exe: ../../bin/gcc\libgpac_static.a(quickjs-libc.o):quickjs-libc.c:(.text+0x53d5): undefined reference to `pipe'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:56: gpac.exe] Error 1
make[2]: Leaving directory '/build/gpac-git/build-32bit/applications/gpac'
make[1]: *** [Makefile:41: apps] Error 2
make[1]: Leaving directory '/build/gpac-git/build-32bit/applications'
make: *** [Makefile:14: all] Error 2
make failed. Check D:/MABS-ffmpeg/build/gpac-git/build-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-Lio.zip
Copy and paste [logs.zip](https://0x0.st/-Lio.zip) in the GitHub issue.

**Comment by 1480c1** [comment]
Caused by https://github.com/gpac/gpac/commit/1320b273879c859cd1ec2a22175effe896fbdef4#diff-6426d528fe98e8a7265725169645cce6c93325f5351f51633289aa980f2fbcd3R3438 and https://github.com/gpac/gpac/commit/fbdc57e0d724c8e7238e018045d176e0e8f9cdcd#diff-6426d528fe98e8a7265725169645cce6c93325f5351f51633289aa980f2fbcd3R73

**Comment by andrewcleveland** [comment]
This seems to be a temporary fix:
[gpac-mingw-pipe.patch.txt](https://github.com/m-ab-s/media-autobuild_suite/files/6627561/gpac-mingw-pipe.patch.txt)
[gpac_extra.sh.txt](https://github.com/m-ab-s/media-autobuild_suite/files/6627562/gpac_extra.sh.txt)

**Comment by andrewcleveland** [comment]
This seems to be a temporary fix:

/build/gpac_extra.sh
```
#!/bin/bash
_pre_configure(){
    do_patch "$LOCALBUILDDIR/gpac-mingw-pipe.patch"
}
```

/build/gpac-mingw-pipe.patch
```
diff --git a/src/quickjs/quickjs-libc.c b/src/quickjs/quickjs-libc.c
index 71958f026..93cb18c6b 100644
--- a/src/quickjs/quickjs-libc.c
+++ b/src/quickjs/quickjs-libc.c
@@ -92,7 +92,6 @@ typedef SSIZE_T ssize_t;
 #endif
 #define popen _popen
 #define pclose _pclose
-#define pipe(_a)  _pipe(_a, 1024, 0)
 
 #if !defined(S_IFIFO)
 #define S_IFIFO _S_IFIFO                     /* Pipe */
@@ -106,6 +105,10 @@ typedef SSIZE_T ssize_t;
 
 #endif
 
+#if defined(_MSC_VER) || defined(__MINGW32__)
+#define pipe(_a)  _pipe(_a, 1024, 0)
+#endif
+
 /* enable the os.Worker API. We rely on GF_Thread */
 #define USE_WORKER
 
```

**Comment by 1480c1** [comment]
Closed in https://github.com/gpac/gpac/commit/3760c5de7227df3dd06c9bcb91b0911844a9d694
